package com.example.wazitoecommerce.navigation

const val HOME_URL = "home"
const val SIGNUP_URL = "signup"
const val LOGIN_URL = "login"
const val ADD_PRODUCTS_URL = "add_products"
const val VIEW_PRODUCTS_URL = "view_products"
const val SPLASH_URL = "Splashscreen"
const val MEAL_URL = "meal"
const val INTRO_URL = "intro"
const val SETTING_URL = "settings"
const val  ADD_EXERCISE_URL= "add_exercise"
const val VIEW_EXERCISE_URL = "view_exercise"
const val WORKOUT_URL = "exercises"
const val PROFILE_URL = "profile"
const val YOUTUBE_URL= "youtube"